name: Collect

on:
  push:
    branches:
      - main

jobs:
  collect:
    name: Collect metrics using central mode of octocov
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Run octocov
        uses: k1LoW/octocov-action@v1    
